### ISSUE TITLE
 异常：流程定义为空 taskType:HTTP

### ISSUE THREAD

**Issue by jiegengmi** [zxcvbnmzsedr/agouti#18]
com.ztianzeng.agouti.core.executor包下
DefaultExecutor类
startWorkFlow方法
**WorkFlowTask.get(task.getTaskType().name())**
调用
com.ztianzeng.agouti.core下WorkFlowTask中的
**public static  WorkFlowTask get(String type) {
        return registry.get(type);
    }**
这个get方法不是永远为空吗？我没看见哪里有put方法

**Comment by zxcvbnmzsedr** [comment]
是子类以构造函数的方式注入的
